services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--log.level=debug'
      - '--log.level=error'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - CDN
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=foo
      - GF_SECURITY_ADMIN_PASSWORD=bar
      - GF_LOG_LEVEL=error
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    networks:
      - CDN

  tier-one-nginx: &nginx
    container_name: tier-one-nginx
    build:
      dockerfile: ./nginx/Dockerfile
    volumes:
      - &nginx_base_volume
        type: bind 
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - &nginx_common_volume
        type: bind
        source: ./nginx/common
        target: /etc/nginx/common
        read_only: true
      - type: bind
        source: ./nginx/tier-one
        target: /etc/nginx/single
        read_only: true
    # ports:
    #   - 9913:9913
    #   - 8080:8080
    networks:
      - CDN
  tier-one-metric-exporter: &nginx-metric-exporter
    container_name: tier-one-metric-exporter
    build:
      dockerfile: ./nginx-vts-exporter/Dockerfile
    depends_on: 
      - prometheus
    entrypoint: 
      - "/usr/local/bin/nginx-vtx-exporter"
      - "-nginx.scrape_uri=http://127.0.0.1:82/status/format/json"
    network_mode: "service:tier-one-nginx"

  tier-two-nginx:
    <<: *nginx
    container_name: tier-two-nginx
    volumes:
      - *nginx_base_volume
      - *nginx_common_volume
      - type: bind
        source: ./nginx/tier-two
        target: /etc/nginx/single
        read_only: true
  tier-two-metric-exporter:
    <<: *nginx-metric-exporter
    container_name: tier-two-metric-exporter
    network_mode: "service:tier-two-nginx"
    depends_on: 
      - tier-two-nginx
  tier-three-nginx:
    <<: *nginx
    container_name: tier-three-nginx
    volumes:
      - *nginx_base_volume
      - *nginx_common_volume
      - type: bind
        source: ./nginx/tier-three
        target: /etc/nginx/single
        read_only: true
    ports:
        - 80:80
  tier-three-metric-exporter:
    <<: *nginx-metric-exporter
    container_name: tier-three-metric-exporter
    network_mode: "service:tier-three-nginx"
    depends_on: 
      - tier-three-nginx

volumes:
  prom_data:

# 172.XX overlaps with my network
networks:
  CDN:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "10.91.0.0/24"
                gateway: "10.91.0.1"